<?php
/**
 * @var \Wizart\General\Block\AbstractButtonsTemplate $block
 */
?>

<?php if ($block->isEnabled()): ?>
<script defer
        class="wizart__entry-point"
        data-vendor_code="<?= $block->getProduct()->getSku(); ?>"
        data-token="<?= $block->getToken(); ?>"
    <?php foreach ($block->getDataAttributes() as $key => $value): ?>
        <?= sprintf('data-%s="%s"', $key, $value); ?>
    <?php endforeach; ?>
        src="<?= $block->getHelper()->getSrc(); ?>"
</script>
<?php endif; ?>